apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-role
  namespace: monitoring
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - delete
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
  - apiGroups: [""]
    resources:
      - configmaps
      - deployments
      - services
    verbs:
      - get
      - create
      - update
      - watch
      - list
      - delete
  - apiGroups: ["apps"]
    resources:
      - configmaps
      - deployments
      - services
    verbs:
      - get
      - create
      - update
      - watch
      - list
      - delete
  - apiGroups: ["k8slab.info"]
    resources:
      - prometheusservers
      - prometheusservers/status
    verbs:
      - get
      - watch
      - list
      - update
      - delete
  - apiGroups: ["extensions"]
    resources:
      - ingress
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-role-binding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-operator-role
  apiGroup: rbac.authorization.k8s.io

